theme: jekyll-theme-minimal
title: 'Introduction to Analysis of Epigenetic Data 2020'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Introduction to the Workshop and the Core
    url: base/welcome
  - title: Schedule
    url: base/schedule

  - heading: Support
  - title: Slack
    url: base/slack
  - title: Zoom
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex

  - heading: Prerequisites
  - title: Introduction to the Command Line
    url: prereqs/CLI_Intro/command-line-intro
  - title: Introduction to R
    url: prereqs/Intro2R/Intro2R_main
