theme: jekyll-theme-minimal
title: 'Introduction to Analysis of Epigenetic Data 2020'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Support
  - title: Slack
    url: base/slack
  - title: Zoom
    url: base/zoom

  - heading: Prerequisites
  - title: Introduction to the Command Line
    url: prereqs/intro-cli
  - title: Introduction to R
    url: prereqs/Intro2R_main
