theme: jekyll-theme-minimal
title: 'Introduction to Analysis of Epigenetic Data 2020'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Introduction to the Workshop and the Core
    url: base/welcome
  - title: Schedule
    url: base/schedule
  - title: What is Bioinformatics/Genomics?
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/genomics/Genomics_a_perspective_May_2020.pdf

  - heading: Support
  - title: Slack
    url: base/slack
  - title: Zoom
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: Introduction to the Command Line
    url: prereqs/CLI_Intro/command-line-intro
  - title: Introduction to R
    url: prereqs/Intro2R/Intro2R_main
  - title: High Performance Computing
    url: prereqs/CLI_Intro/cluster

#  - heading: Data Reduction ChIPseq/ATACseq

#  - heading: Data Analysis ChIPseq/ATACseq

#  - heading: Data Reduction Methylation

#  - heading: Data Analysis Methylation

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2020-Epigenetics_Workshop
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
